import { Order, ServicePrice } from '@/types';

export const STORE_INFO = {
  name: 'SNEAKERCARE LAB',
  tagline: 'Professional Shoe Laundry & Restoration Workshop',
  address: 'Jl. Boulevard Raya Blok Q No. 14, Jakarta Selatan',
  phone: '6281298765432',
  operationalHours: 'Senin - Sabtu: 09:00 - 20:00 WIB',
  instagram: '@sneakercare.lab',
};

export const DEFAULT_SERVICES: ServicePrice[] = [
  {
    id: 'srv-1',
    name: 'Fast Clean',
    category: 'CLEANING',
    description: 'Pembersihan cepat bagian luar (upper & midsole), cocok untuk perawatan rutin.',
    basePrice: 35000,
    estDays: 1,
  },
  {
    id: 'srv-2',
    name: 'Deep Clean Reguler',
    category: 'CLEANING',
    description: 'Pembersihan total menyeluruh: Upper, Insole, Midsole, Outsole, Tali, dan Deodorizer.',
    basePrice: 50000,
    estDays: 3,
  },
  {
    id: 'srv-3',
    name: 'Suede & Nubuck Revival',
    category: 'CLEANING',
    description: 'Pembersihan material sensitif suede tanpa air berlebih, re-nap sikat kawat kuningan & velvet oil.',
    basePrice: 65000,
    estDays: 3,
  },
  {
    id: 'srv-4',
    name: 'Leather Care & Conditioning',
    category: 'CLEANING',
    description: 'Pembersihan bahan kulit asli/sintetis + aplikasi mink oil pelembap agar tidak crack.',
    basePrice: 70000,
    estDays: 3,
  },
  {
    id: 'srv-5',
    name: 'Unyellowing Midsole (UV Light)',
    category: 'RESTORATION',
    description: 'Treatment hidrogen peroksida khusus + pemaparan UV box 24 jam untuk mengembalikan warna sol putih.',
    basePrice: 75000,
    estDays: 4,
  },
  {
    id: 'srv-6',
    name: 'Reglue & Sole Press',
    category: 'RESTORATION',
    description: 'Pengeleman ulang sol menganga/lepas menggunakan primer & adhesive industri serta alat press hidrolik.',
    basePrice: 85000,
    estDays: 4,
  },
  {
    id: 'srv-7',
    name: 'Repaint Upper / Midsole',
    category: 'RESTORATION',
    description: 'Pewarnaan ulang warna pudar menggunakan cat akrilik fleksibel khusus sepatu (Angelus/Tarrago).',
    basePrice: 150000,
    estDays: 5,
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-001',
    orderCode: 'CS-2609-001',
    customerName: 'Bagas Aditya',
    customerPhone: '6281234567890',
    customerAddress: 'Jl. Tebet Barat Dalam No. 42, Jaksel',
    status: 'READY_FOR_PICKUP',
    paymentStatus: 'PAID',
    totalAmount: 120000,
    paidAmount: 120000,
    isExpress: false,
    notes: 'Koleksi pribadi, tolong hati-hati dengan leather vintage.',
    entryDate: '2026-09-06T10:30:00Z',
    targetDate: '2026-09-09T18:00:00Z',
    items: [
      {
        id: 'item-101',
        shoeBrand: 'Nike',
        shoeModel: 'Air Jordan 1 High Lost & Found',
        shoeColor: 'Chicago (Red/White/Black)',
        material: 'LEATHER',
        serviceName: 'Leather Care & Conditioning + Deep Clean',
        serviceId: 'srv-4',
        price: 120000,
        initialNotes: 'Ada noda aspal tipis di midsole kanan, leather collar sedikit kusam.',
        photos: [
          {
            id: 'ph-1',
            photoType: 'BEFORE',
            photoUrl: 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80',
            caption: 'Kondisi awal masuk: noda debu & noda aspal pada midsole.',
            createdAt: '2026-09-06T10:32:00Z',
          },
          {
            id: 'ph-2',
            photoType: 'AFTER',
            photoUrl: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
            caption: 'Hasil setelah treatment: kulit lembut ternutrisi, midsole bersih bebas noda.',
            createdAt: '2026-09-09T14:15:00Z',
          },
        ],
      },
    ],
    statusLogs: [
      { id: 'log-1', status: 'PENDING', notes: 'Pesanan diterima di kasir', changedBy: 'Kasir Rian', createdAt: '2026-09-06T10:30:00Z' },
      { id: 'log-2', status: 'IN_TREATMENT', notes: 'Pembersihan leather cleaner & sikat bulu kuda', changedBy: 'Teknisi Dimas', createdAt: '2026-09-07T09:00:00Z' },
      { id: 'log-3', status: 'DRYING', notes: 'Pengeringan alami dengan sirkulasi udara stabil', changedBy: 'Teknisi Dimas', createdAt: '2026-09-07T16:00:00Z' },
      { id: 'log-4', status: 'QC_PACKING', notes: 'Lolos inspeksi QC, semprot nano protector & parfum bubblegum', changedBy: 'QC Lead Sarah', createdAt: '2026-09-08T15:00:00Z' },
      { id: 'log-5', status: 'READY_FOR_PICKUP', notes: 'Sepatu masuk rak siap ambil no. A-03', changedBy: 'Kasir Rian', createdAt: '2026-09-09T09:30:00Z' },
    ],
  },
  {
    id: 'ord-002',
    orderCode: 'CS-2609-002',
    customerName: 'Dina Ramadhani',
    customerPhone: '6285712345678',
    customerAddress: 'Pancoran Mas, Depok',
    status: 'IN_TREATMENT',
    paymentStatus: 'DOWN_PAYMENT',
    totalAmount: 65000,
    paidAmount: 30000,
    isExpress: false,
    notes: 'Bahan suede jangan sampai mengeras.',
    entryDate: '2026-09-08T13:15:00Z',
    targetDate: '2026-09-11T18:00:00Z',
    items: [
      {
        id: 'item-102',
        shoeBrand: 'New Balance',
        shoeModel: '990v5 Made in USA',
        shoeColor: 'Grey',
        material: 'SUEDE',
        serviceName: 'Suede & Nubuck Revival',
        serviceId: 'srv-3',
        price: 65000,
        initialNotes: 'Bulu suede agak kaku di area toe box kanan, noda air hujan.',
        photos: [
          {
            id: 'ph-3',
            photoType: 'BEFORE',
            photoUrl: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=800&q=80',
            caption: 'Kondisi awal: suede kotor bercak air dan debu jalanan.',
            createdAt: '2026-09-08T13:17:00Z',
          },
        ],
      },
    ],
    statusLogs: [
      { id: 'log-201', status: 'PENDING', notes: 'Pesanan masuk via drop-off', changedBy: 'Kasir Rian', createdAt: '2026-09-08T13:15:00Z' },
      { id: 'log-202', status: 'IN_TREATMENT', notes: 'Dry clean suede sponge & specialized foam', changedBy: 'Teknisi Dimas', createdAt: '2026-09-09T10:00:00Z' },
    ],
  },
  {
    id: 'ord-003',
    orderCode: 'CS-2609-003',
    customerName: 'Kevin Wijaya',
    customerPhone: '6281987654321',
    customerAddress: 'Kemang Pratama, Bekasi',
    status: 'DRYING',
    paymentStatus: 'PAID',
    totalAmount: 70000,
    paidAmount: 70000,
    isExpress: true,
    notes: 'Paket Express 1 hari, diambil sore besok.',
    entryDate: '2026-09-09T08:00:00Z',
    targetDate: '2026-09-10T17:00:00Z',
    items: [
      {
        id: 'item-103',
        shoeBrand: 'Adidas',
        shoeModel: 'Samba OG',
        shoeColor: 'Cloud White / Core Black',
        material: 'LEATHER',
        serviceName: 'Fast Clean + Deep Deodorizer',
        serviceId: 'srv-1',
        price: 70000,
        initialNotes: 'Kondisi lecet pemakaian wajar di bagian tumit belakang.',
        photos: [
          {
            id: 'ph-4',
            photoType: 'BEFORE',
            photoUrl: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&w=800&q=80',
            caption: 'Kondisi awal: outsole dan gum sole kotor tanah basah.',
            createdAt: '2026-09-09T08:05:00Z',
          },
        ],
      },
    ],
    statusLogs: [
      { id: 'log-301', status: 'PENDING', notes: 'Paket Express diterima', changedBy: 'Kasir Rian', createdAt: '2026-09-09T08:00:00Z' },
      { id: 'log-302', status: 'IN_TREATMENT', notes: 'Pencucian kilat selesai dalam 45 menit', changedBy: 'Teknisi Dimas', createdAt: '2026-09-09T09:30:00Z' },
      { id: 'log-303', status: 'DRYING', notes: 'Masuk mesin blower pengering hangat', changedBy: 'Teknisi Dimas', createdAt: '2026-09-09T11:00:00Z' },
    ],
  },
  {
    id: 'ord-004',
    orderCode: 'CS-2609-004',
    customerName: 'Farhan Maulana',
    customerPhone: '6282111223344',
    customerAddress: 'Kebayoran Baru, Jakarta Selatan',
    status: 'QC_PACKING',
    paymentStatus: 'UNPAID',
    totalAmount: 125000,
    paidAmount: 0,
    isExpress: false,
    notes: 'Midsole sudah kuning parah, tolong maksimalkan.',
    entryDate: '2026-09-05T14:20:00Z',
    targetDate: '2026-09-10T18:00:00Z',
    items: [
      {
        id: 'item-104',
        shoeBrand: 'Converse',
        shoeModel: 'Chuck 70 High',
        shoeColor: 'Parchment / Egret',
        material: 'CANVAS',
        serviceName: 'Unyellowing Midsole + Deep Clean',
        serviceId: 'srv-5',
        price: 125000,
        initialNotes: 'Midsole foxing menguning parah karena umur sepatu.',
        photos: [
          {
            id: 'ph-5',
            photoType: 'BEFORE',
            photoUrl: 'https://images.unsplash.com/photo-1607522370275-f14206abe5d3?auto=format&fit=crop&w=800&q=80',
            caption: 'Kondisi awal: karet foxing menguning pekat.',
            createdAt: '2026-09-05T14:22:00Z',
          },
          {
            id: 'ph-6',
            photoType: 'AFTER',
            photoUrl: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
            caption: 'Hasil setelah 2x sesi UV: warna kembali vintage cream bersih.',
            createdAt: '2026-09-09T13:00:00Z',
          },
        ],
      },
    ],
    statusLogs: [
      { id: 'log-401', status: 'PENDING', notes: 'Order masuk kasir', changedBy: 'Kasir Rian', createdAt: '2026-09-05T14:20:00Z' },
      { id: 'log-402', status: 'IN_TREATMENT', notes: 'Aplikasi cairan de-oksidasi & wrap cling film', changedBy: 'Teknisi Dimas', createdAt: '2026-09-06T10:00:00Z' },
      { id: 'log-403', status: 'DRYING', notes: 'Sesi UV Chamber 24 jam', changedBy: 'Teknisi Dimas', createdAt: '2026-09-07T11:00:00Z' },
      { id: 'log-404', status: 'QC_PACKING', notes: 'Pemeriksaan kerataan warna sol, lolos standard', changedBy: 'QC Lead Sarah', createdAt: '2026-09-09T14:00:00Z' },
    ],
  },
  {
    id: 'ord-005',
    orderCode: 'CS-2609-005',
    customerName: 'Anindya Putri',
    customerPhone: '6287890123456',
    customerAddress: 'Bintaro Sektor 7, Tangsel',
    status: 'PENDING',
    paymentStatus: 'UNPAID',
    totalAmount: 135000,
    paidAmount: 0,
    isExpress: false,
    notes: 'Sol samping kiri menganga sekitar 5cm.',
    entryDate: '2026-09-09T11:45:00Z',
    targetDate: '2026-09-13T18:00:00Z',
    items: [
      {
        id: 'item-105',
        shoeBrand: 'Vans',
        shoeModel: 'Old Skool Classic',
        shoeColor: 'Black / White',
        material: 'COMBINATION',
        serviceName: 'Reglue Sole Press + Deep Clean',
        serviceId: 'srv-6',
        price: 135000,
        initialNotes: 'Waffle sole lepas di bagian arch kiri, kanvas kotor debu.',
        photos: [
          {
            id: 'ph-7',
            photoType: 'BEFORE',
            photoUrl: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
            caption: 'Kondisi awal: sol menganga dan lem bawaan getas.',
            createdAt: '2026-09-09T11:47:00Z',
          },
        ],
      },
    ],
    statusLogs: [
      { id: 'log-501', status: 'PENDING', notes: 'Antrean masuk, menunggu antrean teknisi lem', changedBy: 'Kasir Rian', createdAt: '2026-09-09T11:45:00Z' },
    ],
  },
  {
    id: 'ord-006',
    orderCode: 'CS-2609-006',
    customerName: 'Rizky Pratama',
    customerPhone: '6281345678901',
    customerAddress: 'Kalibata City, Jakarta Selatan',
    status: 'COMPLETED',
    paymentStatus: 'PAID',
    totalAmount: 200000,
    paidAmount: 200000,
    isExpress: false,
    notes: 'Repaint hitam pekat di bagian scuff toe box.',
    entryDate: '2026-09-02T09:00:00Z',
    targetDate: '2026-09-07T18:00:00Z',
    completedDate: '2026-09-07T16:30:00Z',
    items: [
      {
        id: 'item-106',
        shoeBrand: 'Nike',
        shoeModel: 'Dunk Low Retro',
        shoeColor: 'Black / White (Panda)',
        material: 'LEATHER',
        serviceName: 'Repaint Toe Box + Deep Clean',
        serviceId: 'srv-7',
        price: 200000,
        initialNotes: 'Cat asli di toe box terkelupas kena gesekan trotoar.',
        photos: [
          {
            id: 'ph-8',
            photoType: 'BEFORE',
            photoUrl: 'https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?auto=format&fit=crop&w=800&q=80',
            caption: 'Kondisi awal: lapisan kulit baret dan warna dasar pudar.',
            createdAt: '2026-09-02T09:05:00Z',
          },
          {
            id: 'ph-9',
            photoType: 'AFTER',
            photoUrl: 'https://images.unsplash.com/photo-1597045566677-8cf032ed6634?auto=format&fit=crop&w=800&q=80',
            caption: 'Hasil repaint: warna hitam pekat menyatu sempurna dengan finishing matte.',
            createdAt: '2026-09-06T17:00:00Z',
          },
        ],
      },
    ],
    statusLogs: [
      { id: 'log-601', status: 'PENDING', notes: 'Diterima di kasir', changedBy: 'Kasir Rian', createdAt: '2026-09-02T09:00:00Z' },
      { id: 'log-602', status: 'IN_TREATMENT', notes: 'Sanding ringan & airbrush 3 lapis warna black matte', changedBy: 'Teknisi Dimas', createdAt: '2026-09-04T11:00:00Z' },
      { id: 'log-603', status: 'DRYING', notes: 'Curing cat 24 jam', changedBy: 'Teknisi Dimas', createdAt: '2026-09-05T14:00:00Z' },
      { id: 'log-604', status: 'QC_PACKING', notes: 'Lolos uji scratch test ringan & anti-crack finisher', changedBy: 'QC Lead Sarah', createdAt: '2026-09-06T16:00:00Z' },
      { id: 'log-605', status: 'READY_FOR_PICKUP', notes: 'Siap diambil di rak B-01', changedBy: 'Kasir Rian', createdAt: '2026-09-06T18:00:00Z' },
      { id: 'log-606', status: 'COMPLETED', notes: 'Pelanggan sudah mengambil dan melunasi pembayaran', changedBy: 'Kasir Rian', createdAt: '2026-09-07T16:30:00Z' },
    ],
  },
];
